[phases.setup]
nixPkgs = ["nodejs_20", "python3", "ffmpeg"]

[phases.install]
cmds = [
  "python3 -m pip install yt-dlp",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production npm start"

[variables]
NODE_ENV = "production"

